# Generated by Django 5.2 on 2025-04-25 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Format: +254XXXXXXXXX', max_length=15)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('assigned_area', models.CharField(max_length=100)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('formation_date', models.DateField()),
                ('meeting_schedule', models.CharField(help_text="E.g., 'Every Monday at 2pm'", max_length=100)),
                ('meeting_location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(help_text='Format: +254XXXXXXXXX', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.CharField(max_length=100)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('next_of_kin_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('field_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True, null=True)),
                ('position', models.CharField(choices=[('MEMBER', 'Regular Member'), ('CHAIR', 'Chairperson'), ('SEC', 'Secretary'), ('TREAS', 'Treasurer'), ('VICE', 'Vice Chairperson')], default='MEMBER', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.member')),
            ],
            options={
                'unique_together': {('member', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='chairperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairperson_of', to='user_management.member'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='user_management.GroupMembership', to='user_management.member'),
        ),
        migrations.AddField(
            model_name='group',
            name='secretary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_of', to='user_management.member'),
        ),
        migrations.AddField(
            model_name='group',
            name='treasurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_of', to='user_management.member'),
        ),
    ]
