# Generated by Django 5.2 on 2025-04-27 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfficerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('po_name', models.CharField(max_length=100)),
                ('group_names', models.TextField()),
                ('total_groups', models.IntegerField()),
                ('total_attendees', models.IntegerField()),
                ('admin_for_group', models.TextField()),
                ('project_registration', models.TextField(blank=True, null=True)),
                ('mem_reg', models.TextField(blank=True, null=True)),
                ('group_loans', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project_loans', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('welfare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Officer Report',
                'verbose_name_plural': 'Field Officer Reports',
                'ordering': ['-date'],
            },
        ),
    ]
