# Generated by Django 5.2 on 2025-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_fieldofficerreport_fines_and_charges_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['member_number']},
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='member_number',
            field=models.PositiveIntegerField(default=0, help_text='Sequential number of member within the group'),
        ),
    ]
