# Generated by Django 5.2 on 2025-04-25 13:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage (e.g. 12.5 for 12.5%)', max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_term', models.IntegerField(help_text='Minimum loan term in months')),
                ('maximum_term', models.IntegerField(help_text='Maximum loan term in months')),
                ('grace_period', models.IntegerField(default=0, help_text='Grace period in days before late fees apply')),
                ('late_payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('individual_eligible', models.BooleanField(default=True)),
                ('group_eligible', models.BooleanField(default=True)),
                ('min_saving_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Minimum percentage of loan amount that must be saved', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage (e.g. 5.25 for 5.25%)', max_digits=5)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('withdrawal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to='user_management.fieldofficer')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to='user_management.fieldofficer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.group')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.member')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tablebanking.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_issued', models.BooleanField(default=False)),
                ('is_synced', models.BooleanField(default=True)),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='tablebanking.loan')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('date_opened', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablebanking.savingsproduct')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('date_opened', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablebanking.savingsproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('INTEREST_EARNED', 'Interest Earned'), ('INTEREST_PAID', 'Interest Paid'), ('FEE', 'Fee'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('field_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
                ('group_savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablebanking.groupsavingsaccount')),
                ('individual_savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablebanking.individualsavingsaccount')),
            ],
        ),
    ]
