# Generated by Django 5.2 on 2025-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'No Recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='NONE', max_length=25),
        ),
    ]
