# Generated by Django 5.2 on 2025-04-25 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('LOAN', 'Loan Product'), ('SAVINGS', 'Savings Product'), ('INVESTMENT', 'Investment Product'), ('INSURANCE', 'Insurance Product'), ('OTHER', 'Other Product')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('launch_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in %', max_digits=5)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('individual_eligible', models.BooleanField(default=True)),
                ('group_eligible', models.BooleanField(default=True)),
                ('minimum_membership_months', models.IntegerField(default=0, help_text='Minimum membership period in months')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTopUpProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('proposal_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ukombozini_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=200)),
                ('estimated_beneficiaries', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.group')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('proposal_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ukombozini_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=200)),
                ('expected_impact', models.TextField()),
                ('field_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.member')),
            ],
        ),
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('term_months', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('field_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.group')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ukombozini_products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('has_receipt', models.BooleanField(default=False)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='project_expenses/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ukombozini_products.grouptopupproject')),
            ],
        ),
    ]
