# Generated by Django 5.2 on 2025-04-25 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('TABLEBAKING', 'Tablebanking Report'), ('LOAN', 'Loan Report'), ('MEMBER', 'Member Report'), ('GROUP', 'Group Report'), ('AGRICULTURE', 'Agriculture Collection Report'), ('SCHOOL_FEES', 'School Fees Collection Report'), ('FINANCIAL', 'Financial Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parameters', models.JSONField(blank=True, help_text='Parameters used to generate the report', null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to='user_management.fieldofficer')),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('query_type', models.CharField(max_length=50)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('parameters_definition', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('TABLEBAKING', 'Tablebanking Report'), ('LOAN', 'Loan Report'), ('MEMBER', 'Member Report'), ('GROUP', 'Group Report'), ('AGRICULTURE', 'Agriculture Collection Report'), ('SCHOOL_FEES', 'School Fees Collection Report'), ('FINANCIAL', 'Financial Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('next_run_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
                ('recipients', models.ManyToManyField(related_name='report_subscriptions', to='user_management.fieldofficer')),
                ('saved_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.savedquery')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('METRIC', 'Metric/KPI'), ('TABLE', 'Data Table'), ('MAP', 'Map'), ('CUSTOM', 'Custom Widget')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart'), ('DONUT', 'Donut Chart'), ('AREA', 'Area Chart'), ('SCATTER', 'Scatter Plot')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_source', models.CharField(max_length=100)),
                ('query', models.TextField(blank=True, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('config', models.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.fieldofficer')),
                ('saved_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.savedquery')),
            ],
        ),
    ]
