name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Setup docs directory if it doesn't exist
        run: |
          if [ ! -d "docs" ]; then
            mkdir -p docs
            echo "# UKOMBOZINI WOMEN MANAGEMENT SYSTEM Documentation" > docs/index.md
            echo "site_name: UKOMBOZINI WOMEN MANAGEMENT SYSTEM" > mkdocs.yml
            echo "theme: material" >> mkdocs.yml
          fi
          
      - name: Build documentation
        run: mkdocs build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site 