name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 30 days. It will be closed in 5 days if there is no activity.'
          stale-pr-message: 'This pull request has been inactive for 30 days. It will be closed in 10 days if there is no activity.'
          close-issue-message: 'This issue was closed due to inactivity.'
          close-pr-message: 'This pull request was closed due to inactivity.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,enhancement,bug,documentation'
          exempt-pr-labels: 'pinned,security,work-in-progress'
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-close: 10
          operations-per-run: 30 