name: Welcome

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing your first issue for the UKOMBOZINI WOMEN MANAGEMENT SYSTEM. 
            
            We appreciate your contribution and will review this as soon as possible.
            
            Please make sure you've checked our documentation and existing issues to see if your question or issue is already addressed.
          pr-message: |
            Hello! Thank you for your first pull request to the UKOMBOZINI WOMEN MANAGEMENT SYSTEM!
            
            We appreciate your contribution and will review your changes as soon as possible.
            
            Please make sure your PR follows our contribution guidelines and includes appropriate tests and documentation. 